### ISSUE TITLE
support SAM api

### ISSUE THREAD

**Issue by aiyou9** [JoOkuma/napari-segment-anything#15]
https://github.com/ksugar/samapi

https://github.com/ksugar/qupath-extension-sam

**Comment by JoOkuma** [comment]
Hi @aiyou9, is there any question? Otherwise, I'll close this issue.

**Comment by aiyou9** [comment]
> Hi @aiyou9, is there any question? Otherwise, I'll close this issue.

no question ，just an advise 
support SAM run in remote，local computer run SAM which is hard
