### ISSUE TITLE
Add Mac GPU Support 

### ISSUE THREAD

**Issue by frankblubaugh** [JoOkuma/napari-segment-anything#8]
add mac gpu support if available

**Comment by frankblubaugh** [comment]
Adding this to _widget.py around line 32 should solve it. I can't figure out github's pull request nonsense:
`        if torch.cuda.is_available():
          self._device = "cuda"
        elif torch.backends.mps.is_available():
          self._device = "mps"
        else:
          self._device = "cpu"
`

**Comment by JoOkuma** [comment]
My colleague tested it, closed #9
